# Generated by Django 5.2.12 on 2026-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
