# Generated by Django 5.2.12 on 2026-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_accounts", "0002_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
