# Generated by Django 5.2.12 on 2026-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
