# Generated by Django 5.2.12 on 2026-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_docs", "0002_alter_document_deleted_at_alter_document_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_exporting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdfs/"),
        ),
    ]
