# Generated by Django 5.2.12 on 2026-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='slug',
        ),
    ]
