# Generated by Django 5.2.12 on 2026-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_workspaces", "0003_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
